### ISSUE TITLE
Include used options for each codec

### ISSUE THREAD

**Issue by shrx** [quixdb/squash-benchmark-web#9]
Could you provide a table with compression/decompression options that were used with each codec for benchmarking?

**Comment by nemequ** [comment]
All codecs are benchmarked using the default options; only the level varies.

**Comment by nemequ** [comment]
So it just occurred to me that you may be referring to compiler options, not the codec options.  If so, https://quixdb.github.io/squash-benchmark/#faq-compiler-flags

That will change a bit for the next release; I'll drop `-march=native -mtune=native` since that's not an option for most people.  I'll also have to drop `-flto` because of [a bug in CMake](https://gitlab.kitware.com/cmake/cmake/issues/15939).  In the past it wasn't a problem, but we're trying to integrate library's build systems where possible, which means we end up linking plugins to a static library, and for LTO that requires using `gcc-ar` instead of `ar`, so we can't just add `-flto` to our cflags anymore.  So basically, we're back to just `-O3` until CMake gets fixed.

**Comment by shrx** [comment]
Actually I was referring to the codec options. Thanks for the explanation.
